version: "3"
services:
  app:
    build: 
      context: .
      Dockerfile: app/Dockerfile 
    env_file: postgres/postgres.env
    environment: 
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
  db:
    image: postgres:9.6-alpine
    restart: always
    env_file: postgres/postgres.env
    ports:
    - 5432:5432
